### ISSUE TITLE
Sorting Algorithm - Selection Sort in Python

### ISSUE THREAD

**Issue by silicolicious** [neha07kumari/Mini_Python_Projects#1]
Hi Neha Kumari!
I am Mageshkrishna R and I have registered in Hacktoberfest.
I would like to contribute on your repository on the topic:-
- Selection Sort

Assign it to me.
Thank you!

**Comment by neha07kumari** [comment]
@silicolicious  assigned. Please follow the rules & steps.

**Comment by silicolicious** [comment]
> @silicolicious assigned. Please follow the rules & steps.

![image](https://user-images.githubusercontent.com/74927399/135480239-6d9d5dda-edc5-402b-9d2b-2a346c31dd18.png)

I am still not assigned, please assign it to me.

**Comment by srijan-singh** [comment]
Hello @neha07kumari!
I've registered in Hacktoberfest 2021 and this is my first time to contribute in opensource and I would like to contribute on this topic. I've earned 4 stars in Python from Hackerrank and I'm pretty confident that I am able to do it.

**Comment by neha07kumari** [comment]
@srijan-singh @saisumanthkumar  this issue has already been assigned to @silicolicious . Do read the "rules for contribution" in README.md
Issues are assigned on first come first serve basis.🙂
You'll can go put up another different issues.
