### ISSUE TITLE
Interview Preparation Kit for Python Programmers

### ISSUE THREAD

**Issue by Varun270** [neha07kumari/Mini_Python_Projects#105]
A separate folder with a List of Interview questions from FAANGM companies with their Optimal solution in Python.
And Some interview tips from amazon's best-seller - "Cracking The Coding interview Book".

**Comment by Varun270** [comment]
I would Like to work on this issue please assign it to me under the hacktoberfest2021 label.

**Comment by neha07kumari** [comment]
@Varun270  This repo only allows mini projects in python and data structures and algorithms questions.
You cannot put whole questions under one folder.
As of now you are only allowed to put one single algorithm question.
