### ISSUE TITLE
Bubble Sort in Python

### ISSUE THREAD

**Issue by Varun270** [neha07kumari/Mini_Python_Projects#114]
Implementation of Bubble sort Algorithm in python

**Comment by Varun270** [comment]
@neha07kumari I would like to work on this issue. Please assign it to me under hacktoberfest tag.

**Comment by Varun270** [comment]
<img width="397" alt="bubble_sort_error" src="https://user-images.githubusercontent.com/75975268/135871241-c083c69a-8d85-4096-b20c-1497bd896466.png">

**Comment by neha07kumari** [comment]
yep

**Comment by Varun270** [comment]
Done !!
