### ISSUE TITLE
Binary Search In Python

### ISSUE THREAD

**Issue by AlphaVS-76** [neha07kumari/Mini_Python_Projects#116]
This would contain the code for Binary search in Python and parallel to it would be it's explanation as well.

**Comment by AlphaVS-76** [comment]
@neha07kumari Please assign me this Issue! Also would be very grateful if you could tag this issue as Hacktoberfest-accepted

**Comment by justinseby** [comment]
Would you please assign this to me?

**Comment by AlphaVS-76** [comment]
@justinseby its already been assigned to me
