### ISSUE TITLE
GUI based Multiplayer Game

### ISSUE THREAD

**Issue by Ankit1598** [neha07kumari/Mini_Python_Projects#22]
Hey @neha07kumari, I would like to add a GUI based multiplayer rock-paper-scissor game, which uses socket make connections between 2 clients.

Rooms are auto configured to occupy only 2 users at a time so we can start multiple instances at the same time.

Please assign me this issue.

**Comment by neha07kumari** [comment]
@Ankit1598  Issue has already being assigned. 
You can go for some other.

**Comment by neha07kumari** [comment]
@Ankit1598  Issue has already being assigned. 
You can go for some other.
