### ISSUE TITLE
Folder Beautifier

### ISSUE THREAD

**Issue by diwash007** [neha07kumari/Mini_Python_Projects#23]
I would like to add a program that will manage the files on a giver folder path by dividing them into specific folders. It will be useful for someone with messy folders with lots of files.

**Comment by phileinSophos** [comment]
can I work on this issue

**Comment by neha07kumari** [comment]
> can I work on this issue

@phileinSophos  Please read the rules for contribution in README.md.
Issues are assigned on first come first basis.
You can open up some other issue.
