### ISSUE TITLE
want to create program to check whether the given string is palindrome or not

### ISSUE THREAD

**Issue by Chiranjeev-droid** [neha07kumari/Mini_Python_Projects#35]

**Comment by Chiranjeev-droid** [comment]
HI, I have contributed the program . Please accept the pull request #34 . I had also added my name & place in the contributers.md file as written in the rules

**Comment by Aviace** [comment]
Hey, I am a beginner in open source and hv participated in hacktoberfest. I can confidently solve this issue. This technically will be my first open source project in python if assigned to me. Hopes. Thanks.

**Comment by Aviace** [comment]
Actually I know its assigned already, but I don't know whether after that even can anyone else again ask for assignment of the same issue?

**Comment by neha07kumari** [comment]
> Actually I know its assigned already, but I don't know whether after that even can anyone else again ask for assignment of the same issue?

@Aviace  No.
you need to make a different issue problem(non-duplicate)

**Comment by Aviace** [comment]
Okay, thanks.
