### ISSUE TITLE
Random Password Generator

### ISSUE THREAD

**Issue by UG-SEP** [neha07kumari/Mini_Python_Projects#48]
Hey @neha07kumari,
I wanted to add a Random password generator on the basis of some criteria under Hacktoberfeast
Please assign it to me
Thanks😊

**Comment by Aviace** [comment]
Hey @neha07kumari , I can add a random password generator. This would be my first hacktoberfest and open source project to work upon. So please give me a chance and assign me this issue.

**Comment by neha07kumari** [comment]
This issue has been done.
Kindly put up a non-duplicate issue.
