### ISSUE TITLE
Random password generator

### ISSUE THREAD

**Issue by R055A** [neha07kumari/Mini_Python_Projects#5]
I am requesting to contribute a simple random password generator for Hacktoberfest.

**Comment by neha07kumari** [comment]
Assigned to @R055A . Please follow the rules & steps.

**Comment by srijan-singh** [comment]
Hello @neha07kumari!
I've registered in Hacktoberfest 2021 and this is my first time to contribute in opensource and I would like to contribute on this topic. I've earned 4 stars in Python from Hackerrank and I'm pretty confident that I am able to do it.

**Comment by SanthoshS20** [comment]
@R055A  Can you assign it to me?

**Comment by kunal-mahatha** [comment]
Please assign the task.

**Comment by neha07kumari** [comment]
@srijan-singh  @SanthoshS20  @kunal-mahatha  this issue has already been assigned to @R055A  . Do read the "rules for contribution" in README.md
Issues are assigned on first come first serve basis.🙂
You'll can go put up another different issues.

**Comment by R055A** [comment]
> 
> 
> Assigned to @R055A . Please follow the rules & steps.

Thank you. Should I make a new PR?

**Comment by tausiq2003** [comment]
should I contribute please reply.

**Comment by neha07kumari** [comment]
> > Assigned to @R055A . Please follow the rules & steps.
> 
> Thank you. Should I make a new PR?

No!! I'll merge the previous one.

**Comment by neha07kumari** [comment]
> should I contribute please reply.

Sorry!! No!! 
Issue has already being assigned.
