### ISSUE TITLE
Heap Sort in python

### ISSUE THREAD

**Issue by NitikaGupta16** [neha07kumari/Mini_Python_Projects#7]
I am participating in hacktoberfest 2021. I would like to add heap sort algorithm in python. Please assign me this issue.

**Comment by neha07kumari** [comment]
Assigned to @NitikaGupta16 . Please  do follow the steps & rules.

**Comment by srijan-singh** [comment]
Hello @neha07kumari!
I've registered in Hacktoberfest 2021 and this is my first time to contribute in opensource and I would like to contribute on this topic. I've earned 4 stars in Python from Hackerrank and I'm pretty confident that I am able to do it.
